post:
  default:
    template: |
      ## 🧪 Smoke Test Results

      The github-comment action is working correctly! ✅

      - **Commit**: {{ .Commit.SHA }}
      - **PR Number**: {{ .PullRequest.Number }}
      - **Repository**: {{ .Repo.Owner }}/{{ .Repo.Name }}

      This comment was posted automatically by the CI workflow as a smoke test.
